[package]
name = "pytoid"
version = "0.0.9-alpha"
authors = ["masashi yoshikawa <earnest.marshi@gmail.com>"]
edition = "2018"

[lib]
name = "toid"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { path = "./pyo3", features = ["extension-module"] }
serde_json = "1.0"
numpy = "0.9.0"
# toid = "0.5.0-alpha"
toid = { path = "../toid"  }
