[package]
name = "pytoid"
version = "0.0.8-alpha"
authors = ["masashi yoshikawa <earnest.marshi@gmail.com>"]
edition = "2018"

[lib]
name = "toid"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { path = "./pyo3", features = ["extension-module"] }
serde_json = "1.0"
# toid = "0.4.0-alpha"
toid = { git = "https://github.com/YoshikawaMasashi/toid.git", branch = "develop"  }
